"""initial schema

Revision ID: 40b01257bc89
Revises: 
Create Date: 2026-07-14 06:21:07.189239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40b01257bc89'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('awards',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.Enum('團體', '個人', name='award_kind', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('has_presentation', sa.Boolean(), nullable=False),
    sa.Column('is_weighted', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_awards'))
    )
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('attribute', sa.Enum('自治性', '學藝性', '服務性', '聯誼性', '藝術性', '體育性', name='club_attribute', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('intro', sa.Text(), nullable=False),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('advisor_name', sa.Text(), nullable=True),
    sa.Column('advisor_dept', sa.Text(), nullable=True),
    sa.Column('advisor_email', sa.Text(), nullable=True),
    sa.Column('advisor_ext', sa.Text(), nullable=True),
    sa.Column('suspended_until', sa.Date(), nullable=True),
    sa.Column('suspend_reason', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clubs')),
    sa.UniqueConstraint('name', name=op.f('uq_clubs_name'))
    )
    op.create_table('email_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_addr', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('sent', 'failed', name='email_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_logs'))
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('一般', '電子設備', '投影布幕', '帳篷', name='equipment_category', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('total_qty', sa.Integer(), nullable=False),
    sa.Column('needs_serial', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment')),
    sa.UniqueConstraint('name', name=op.f('uq_equipment_name'))
    )
    op.create_table('eval_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eval_groups'))
    )
    op.create_index(op.f('ix_eval_groups_year'), 'eval_groups', ['year'], unique=False)
    op.create_table('holidays',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('date', name=op.f('pk_holidays'))
    )
    op.create_table('legacy_id_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legacy_system', sa.Enum('cms', 'clubclass', name='legacy_system', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('legacy_table', sa.Text(), nullable=False),
    sa.Column('legacy_id', sa.Text(), nullable=False),
    sa.Column('new_table', sa.Text(), nullable=False),
    sa.Column('new_id', sa.Text(), nullable=False),
    sa.Column('migrated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legacy_id_map')),
    sa.UniqueConstraint('legacy_system', 'legacy_table', 'legacy_id', name=op.f('uq_legacy_id_map_legacy_system'))
    )
    op.create_table('system_settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_system_settings'))
    )
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('category', sa.Enum('教室', '練習空間', '廣場戶外', name='venue_category', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('allow_fixed', sa.Boolean(), nullable=False),
    sa.Column('allow_temp', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venues')),
    sa.UniqueConstraint('name', name=op.f('uq_venues_name'))
    )
    op.create_table('award_rubric_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('award_id', sa.Text(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('group_label', sa.Text(), nullable=True),
    sa.Column('group_weight', sa.Float(), nullable=True),
    sa.Column('item_key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('help', sa.Text(), nullable=False),
    sa.Column('is_admin_item', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['award_id'], ['awards.id'], name=op.f('fk_award_rubric_items_award_id_awards')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_award_rubric_items')),
    sa.UniqueConstraint('award_id', 'year', 'item_key', name=op.f('uq_award_rubric_items_award_id'))
    )
    op.create_table('club_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('student_id', sa.Text(), nullable=False),
    sa.Column('kind', sa.Enum('幹部', '社員', name='member_kind', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_club_members_club_id_clubs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_members')),
    sa.UniqueConstraint('club_id', 'student_id', name=op.f('uq_club_members_club_id'))
    )
    op.create_table('eval_group_clubs',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_eval_group_clubs_club_id_clubs')),
    sa.ForeignKeyConstraint(['group_id'], ['eval_groups.id'], name=op.f('fk_eval_group_clubs_group_id_eval_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'club_id', name=op.f('pk_eval_group_clubs'))
    )
    op.create_table('eval_settings',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('award_id', sa.Text(), nullable=False),
    sa.Column('comment_released', sa.Boolean(), nullable=False),
    sa.Column('unlocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['award_id'], ['awards.id'], name=op.f('fk_eval_settings_award_id_awards')),
    sa.PrimaryKeyConstraint('year', 'award_id', name=op.f('pk_eval_settings'))
    )
    op.create_table('maintenance_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('items', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'done', name='maintenance_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('handle_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_maintenance_requests_club_id_clubs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance_requests'))
    )
    op.create_index(op.f('ix_maintenance_requests_club_id'), 'maintenance_requests', ['club_id'], unique=False)
    op.create_table('officer_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('term', sa.Text(), nullable=False),
    sa.Column('position', sa.Enum('社長或會長', '副社長或副會長', name='cert_position', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('applicant_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='booking_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_officer_certificates_club_id_clubs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_officer_certificates'))
    )
    op.create_index(op.f('ix_officer_certificates_club_id'), 'officer_certificates', ['club_id'], unique=False)
    op.create_table('postal_account_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('reasons', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('account_name', sa.Text(), nullable=False),
    sa.Column('account_number', sa.Text(), nullable=False),
    sa.Column('new_agent_name', sa.Text(), nullable=True),
    sa.Column('new_agent_phone', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='booking_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_postal_account_changes_club_id_clubs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_postal_account_changes'))
    )
    op.create_index(op.f('ix_postal_account_changes_club_id'), 'postal_account_changes', ['club_id'], unique=False)
    op.create_table('room_booking_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='booking_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_room_booking_requests_club_id_clubs')),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_room_booking_requests_venue_id_venues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_booking_requests'))
    )
    op.create_index(op.f('ix_room_booking_requests_club_id'), 'room_booking_requests', ['club_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'staff', 'club', 'viewer', name='user_role', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('auth_provider', sa.Enum('local', 'sso', name='auth_provider', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('is_super', sa.Boolean(), nullable=False),
    sa.Column('permissions', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('can_view_eval', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_users_club_id_clubs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('venue_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('periods', postgresql.ARRAY(sa.String(length=2)), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='booking_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_venue_bookings_club_id_clubs')),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_venue_bookings_venue_id_venues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venue_bookings'))
    )
    op.create_index(op.f('ix_venue_bookings_club_id'), 'venue_bookings', ['club_id'], unique=False)
    op.create_index('ix_venue_bookings_venue_date', 'venue_bookings', ['venue_id', 'date'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('社課', '活動', '會議', name='activity_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('is_large', sa.Boolean(), nullable=False),
    sa.Column('is_large_approved', sa.Boolean(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('participants_in', sa.Integer(), nullable=False),
    sa.Column('participants_out', sa.Integer(), nullable=False),
    sa.Column('staff_text', sa.Text(), nullable=False),
    sa.Column('fund_source', sa.Text(), nullable=True),
    sa.Column('school_approved', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'pending_advisor', 'pending_chief', 'pending_dean', 'approved', 'rejected', 'closing_pending_advisor', 'closed', name='activity_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('close_unlocked', sa.Boolean(), nullable=False),
    sa.Column('close_draft', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_activities_club_id_clubs')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_activities_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities'))
    )
    op.create_index('ix_activities_club_status', 'activities', ['club_id', 'status'], unique=False)
    op.create_index('ix_activities_date', 'activities', ['date'], unique=False)
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('target_type', sa.Enum('all', 'attr', 'club', name='announcement_target', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('target_value', sa.Text(), nullable=True),
    sa.Column('is_auto', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_announcements_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_announcements'))
    )
    op.create_table('approval_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.Enum('activity', 'activity_close', 'room_booking', 'venue_booking', 'equipment_loan', 'officer_cert', 'postal_change', 'maintenance', 'signup', name='approval_subject', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('decision', sa.Enum('approve', 'reject', 'unlock', 'revoke', name='approval_decision', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_approval_records_actor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_records'))
    )
    op.create_index('ix_approval_records_subject', 'approval_records', ['subject_type', 'subject_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('equipment_loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'checked_out', 'returned', name='loan_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('checkout_by', sa.Integer(), nullable=True),
    sa.Column('checkout_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('serials', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('checkin_by', sa.Integer(), nullable=True),
    sa.Column('checkin_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checkin_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checkin_by'], ['users.id'], name=op.f('fk_equipment_loans_checkin_by_users')),
    sa.ForeignKeyConstraint(['checkout_by'], ['users.id'], name=op.f('fk_equipment_loans_checkout_by_users')),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_equipment_loans_club_id_clubs')),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_equipment_loans_equipment_id_equipment')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment_loans'))
    )
    op.create_index('ix_equipment_loans_club_status', 'equipment_loans', ['club_id', 'status'], unique=False)
    op.create_index(op.f('ix_equipment_loans_equipment_id'), 'equipment_loans', ['equipment_id'], unique=False)
    op.create_table('eval_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('award_id', sa.Text(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('admin_score_override', 'merit_bonus', 'final_override', 'award_override', name='adjustment_kind', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_eval_adjustments_actor_id_users')),
    sa.ForeignKeyConstraint(['award_id'], ['awards.id'], name=op.f('fk_eval_adjustments_award_id_awards')),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_eval_adjustments_club_id_clubs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eval_adjustments'))
    )
    op.create_index('ix_eval_adjustments_year_club', 'eval_adjustments', ['year', 'club_id'], unique=False)
    op.create_table('eval_group_reviewers',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['eval_groups.id'], name=op.f('fk_eval_group_reviewers_group_id_eval_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_eval_group_reviewers_user_id_users')),
    sa.PrimaryKeyConstraint('group_id', 'user_id', name=op.f('pk_eval_group_reviewers'))
    )
    op.create_table('files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.Text(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('slot', sa.Text(), nullable=True),
    sa.Column('original_name', sa.Text(), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('mime', sa.Text(), nullable=False),
    sa.Column('sha256', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_files_club_id_clubs')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_files_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_files'))
    )
    op.create_index('ix_files_club_sha256', 'files', ['club_id', 'sha256'], unique=False)
    op.create_index('ix_files_subject', 'files', ['subject_type', 'subject_id'], unique=False)
    op.create_table('password_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_history_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_history'))
    )
    op.create_index(op.f('ix_password_history_user_id'), 'password_history', ['user_id'], unique=False)
    op.create_table('review_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('award_id', sa.Text(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('presentation_score', sa.Integer(), nullable=True),
    sa.Column('bonus', sa.Integer(), nullable=False),
    sa.Column('penalty', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['award_id'], ['awards.id'], name=op.f('fk_review_scores_award_id_awards')),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_review_scores_club_id_clubs')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_review_scores_reviewer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_scores')),
    sa.UniqueConstraint('year', 'award_id', 'club_id', 'reviewer_id', name=op.f('uq_review_scores_year'))
    )
    op.create_table('room_booking_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('period', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['room_booking_requests.id'], name=op.f('fk_room_booking_slots_request_id_room_booking_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_booking_slots'))
    )
    op.create_index('ix_room_booking_slots_date_period', 'room_booking_slots', ['date', 'period'], unique=False)
    op.create_index(op.f('ix_room_booking_slots_request_id'), 'room_booking_slots', ['request_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('csrf_token', sa.Text(), nullable=False),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('signup_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('time_text', sa.Text(), nullable=True),
    sa.Column('place', sa.Text(), nullable=True),
    sa.Column('audience', sa.Text(), nullable=True),
    sa.Column('allow_multiple', sa.Boolean(), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('kind', sa.Enum('normal', 'cadre_training', 'leader_meeting', name='signup_kind', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('session_based', sa.Boolean(), nullable=False),
    sa.Column('requires_confirmation', sa.Boolean(), nullable=False),
    sa.Column('is_eval', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_signup_items_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signup_items'))
    )
    op.create_index(op.f('ix_signup_items_year'), 'signup_items', ['year'], unique=False)
    op.create_table('violations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('items', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('other', sa.Text(), nullable=True),
    sa.Column('filler_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'resolved', name='violation_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('resolve_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_violations_club_id_clubs')),
    sa.ForeignKeyConstraint(['filler_id'], ['users.id'], name=op.f('fk_violations_filler_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_violations'))
    )
    op.create_index('ix_violations_club_status', 'violations', ['club_id', 'status'], unique=False)
    op.create_table('activity_budget_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('self_fund', sa.Integer(), nullable=False),
    sa.Column('requested_subsidy', sa.Integer(), nullable=False),
    sa.Column('approved_subsidy', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_activity_budget_items_activity_id_activities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_budget_items'))
    )
    op.create_index(op.f('ix_activity_budget_items_activity_id'), 'activity_budget_items', ['activity_id'], unique=False)
    op.create_table('activity_reports',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('non_member_count', sa.Integer(), nullable=False),
    sa.Column('actual_start', sa.Time(), nullable=False),
    sa.Column('actual_end', sa.Time(), nullable=False),
    sa.Column('actual_location', sa.Text(), nullable=False),
    sa.Column('highlights', sa.Text(), nullable=False),
    sa.Column('goals', sa.Text(), nullable=False),
    sa.Column('others', sa.Text(), nullable=False),
    sa.Column('review_meeting', sa.Boolean(), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('expense', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_activity_reports_activity_id_activities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('activity_id', name=op.f('pk_activity_reports'))
    )
    op.create_table('eval_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('rubric_item_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_eval_uploads_club_id_clubs')),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_eval_uploads_file_id_files')),
    sa.ForeignKeyConstraint(['rubric_item_id'], ['award_rubric_items.id'], name=op.f('fk_eval_uploads_rubric_item_id_award_rubric_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eval_uploads'))
    )
    op.create_index('ix_eval_uploads_year_club', 'eval_uploads', ['year', 'club_id'], unique=False)
    op.create_table('review_score_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score_id', sa.Integer(), nullable=False),
    sa.Column('rubric_item_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rubric_item_id'], ['award_rubric_items.id'], name=op.f('fk_review_score_items_rubric_item_id_award_rubric_items')),
    sa.ForeignKeyConstraint(['score_id'], ['review_scores.id'], name=op.f('fk_review_score_items_score_id_review_scores'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_score_items')),
    sa.UniqueConstraint('score_id', 'rubric_item_id', name=op.f('uq_review_score_items_score_id'))
    )
    op.create_table('signup_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('participants', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_signup_drafts_club_id_clubs')),
    sa.ForeignKeyConstraint(['item_id'], ['signup_items.id'], name=op.f('fk_signup_drafts_item_id_signup_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signup_drafts')),
    sa.UniqueConstraint('item_id', 'club_id', name=op.f('uq_signup_drafts_item_id'))
    )
    op.create_index(op.f('ix_signup_drafts_club_id'), 'signup_drafts', ['club_id'], unique=False)
    op.create_table('signup_item_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('semester', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['signup_items.id'], name=op.f('fk_signup_item_sessions_item_id_signup_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signup_item_sessions'))
    )
    op.create_index(op.f('ix_signup_item_sessions_item_id'), 'signup_item_sessions', ['item_id'], unique=False)
    op.create_table('signups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_signups_club_id_clubs')),
    sa.ForeignKeyConstraint(['item_id'], ['signup_items.id'], name=op.f('fk_signups_item_id_signup_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signups')),
    sa.UniqueConstraint('item_id', 'club_id', name=op.f('uq_signups_item_id'))
    )
    op.create_index(op.f('ix_signups_club_id'), 'signups', ['club_id'], unique=False)
    op.create_table('activity_reflections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.Text(), nullable=False),
    sa.Column('dept', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['activity_reports.activity_id'], name=op.f('fk_activity_reflections_report_id_activity_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_reflections'))
    )
    op.create_index(op.f('ix_activity_reflections_report_id'), 'activity_reflections', ['report_id'], unique=False)
    op.create_table('session_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('attended', sa.Boolean(), nullable=False),
    sa.Column('marked_by', sa.Integer(), nullable=False),
    sa.Column('marked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_session_attendance_club_id_clubs')),
    sa.ForeignKeyConstraint(['marked_by'], ['users.id'], name=op.f('fk_session_attendance_marked_by_users')),
    sa.ForeignKeyConstraint(['session_id'], ['signup_item_sessions.id'], name=op.f('fk_session_attendance_session_id_signup_item_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_attendance')),
    sa.UniqueConstraint('session_id', 'club_id', name=op.f('uq_session_attendance_session_id'))
    )
    op.create_index(op.f('ix_session_attendance_club_id'), 'session_attendance', ['club_id'], unique=False)
    op.create_table('signup_awards',
    sa.Column('signup_id', sa.Integer(), nullable=False),
    sa.Column('award_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['award_id'], ['awards.id'], name=op.f('fk_signup_awards_award_id_awards')),
    sa.ForeignKeyConstraint(['signup_id'], ['signups.id'], name=op.f('fk_signup_awards_signup_id_signups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('signup_id', 'award_id', name=op.f('pk_signup_awards'))
    )
    op.create_table('signup_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signup_id', sa.Integer(), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signup_id'], ['signups.id'], name=op.f('fk_signup_entries_signup_id_signups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signup_entries'))
    )
    op.create_index(op.f('ix_signup_entries_signup_id'), 'signup_entries', ['signup_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signup_entries_signup_id'), table_name='signup_entries')
    op.drop_table('signup_entries')
    op.drop_table('signup_awards')
    op.drop_index(op.f('ix_session_attendance_club_id'), table_name='session_attendance')
    op.drop_table('session_attendance')
    op.drop_index(op.f('ix_activity_reflections_report_id'), table_name='activity_reflections')
    op.drop_table('activity_reflections')
    op.drop_index(op.f('ix_signups_club_id'), table_name='signups')
    op.drop_table('signups')
    op.drop_index(op.f('ix_signup_item_sessions_item_id'), table_name='signup_item_sessions')
    op.drop_table('signup_item_sessions')
    op.drop_index(op.f('ix_signup_drafts_club_id'), table_name='signup_drafts')
    op.drop_table('signup_drafts')
    op.drop_table('review_score_items')
    op.drop_index('ix_eval_uploads_year_club', table_name='eval_uploads')
    op.drop_table('eval_uploads')
    op.drop_table('activity_reports')
    op.drop_index(op.f('ix_activity_budget_items_activity_id'), table_name='activity_budget_items')
    op.drop_table('activity_budget_items')
    op.drop_index('ix_violations_club_status', table_name='violations')
    op.drop_table('violations')
    op.drop_index(op.f('ix_signup_items_year'), table_name='signup_items')
    op.drop_table('signup_items')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_room_booking_slots_request_id'), table_name='room_booking_slots')
    op.drop_index('ix_room_booking_slots_date_period', table_name='room_booking_slots')
    op.drop_table('room_booking_slots')
    op.drop_table('review_scores')
    op.drop_index(op.f('ix_password_history_user_id'), table_name='password_history')
    op.drop_table('password_history')
    op.drop_index('ix_files_subject', table_name='files')
    op.drop_index('ix_files_club_sha256', table_name='files')
    op.drop_table('files')
    op.drop_table('eval_group_reviewers')
    op.drop_index('ix_eval_adjustments_year_club', table_name='eval_adjustments')
    op.drop_table('eval_adjustments')
    op.drop_index(op.f('ix_equipment_loans_equipment_id'), table_name='equipment_loans')
    op.drop_index('ix_equipment_loans_club_status', table_name='equipment_loans')
    op.drop_table('equipment_loans')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_approval_records_subject', table_name='approval_records')
    op.drop_table('approval_records')
    op.drop_table('announcements')
    op.drop_index('ix_activities_date', table_name='activities')
    op.drop_index('ix_activities_club_status', table_name='activities')
    op.drop_table('activities')
    op.drop_index('ix_venue_bookings_venue_date', table_name='venue_bookings')
    op.drop_index(op.f('ix_venue_bookings_club_id'), table_name='venue_bookings')
    op.drop_table('venue_bookings')
    op.drop_table('users')
    op.drop_index(op.f('ix_room_booking_requests_club_id'), table_name='room_booking_requests')
    op.drop_table('room_booking_requests')
    op.drop_index(op.f('ix_postal_account_changes_club_id'), table_name='postal_account_changes')
    op.drop_table('postal_account_changes')
    op.drop_index(op.f('ix_officer_certificates_club_id'), table_name='officer_certificates')
    op.drop_table('officer_certificates')
    op.drop_index(op.f('ix_maintenance_requests_club_id'), table_name='maintenance_requests')
    op.drop_table('maintenance_requests')
    op.drop_table('eval_settings')
    op.drop_table('eval_group_clubs')
    op.drop_table('club_members')
    op.drop_table('award_rubric_items')
    op.drop_table('venues')
    op.drop_table('system_settings')
    op.drop_table('legacy_id_map')
    op.drop_table('holidays')
    op.drop_index(op.f('ix_eval_groups_year'), table_name='eval_groups')
    op.drop_table('eval_groups')
    op.drop_table('equipment')
    op.drop_table('email_logs')
    op.drop_table('clubs')
    op.drop_table('awards')
    # ### end Alembic commands ###
